'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH "ceylon browse" 1 "18 August 2017" "" ""
.SH NAME
ceylon browse \- Open module documentation in the browser
.SH SYNOPSIS
'nh
.fi
.ad l
\fBceylon browse\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[--cacherep=\fIurl\fR] [--cwd=\fIdir\fR] [--maven-overrides=\fIfile\fR] [--no-default-repositories] [--offline] [--overrides=\fIfile\fR] [--rep=\fIurl\fR...] [--sysrep=\fIurl\fR] [--timeout=\fIseconds\fR] [--verbose[=\fIflags\fR]] [--] {module}\&...
'in \n(.iu-\nxu
.ad b
'hy
.SH OPTIONS
.TP 
--cacherep=\fIurl\fR
Specifies the folder to use for caching downloaded modules. (default: \*(T<~/.ceylon/cache\*(T>)
.TP 
--cwd=\fIdir\fR
Specifies the current working directory for this tool. (default: the directory where the tool is run from)
.TP 
--maven-overrides=\fIfile\fR
Specifies the XML file to use to load Maven artifact overrides. See http://ceylon-lang.org/documentation/current/reference/repository/maven/ for information. Deprecated: use --overrides.
.TP 
--no-default-repositories
Indicates that the default repositories should not be used.
.TP 
--offline, -L
Enables offline mode that will prevent connections to remote repositories.
.TP 
--overrides=\fIfile\fR, -O \fIfile\fR
Specifies the XML file to use to load module overrides. See http://ceylon-lang.org/documentation/current/reference/repository/maven/ for information. \fInull\fR.
.TP 
--rep=\fIurl\fR
Specifies a module repository containing dependencies. Can be specified multiple times. (default: \*(T<modules\*(T>, \*(T<~/.ceylon/repo\*(T>, \*(T<https://modules.ceylon\-lang.org/repo/1\*(T>)
.TP 
--sysrep=\fIurl\fR
Specifies the system repository containing essential modules. (default: \*(T<$CEYLON_HOME/repo\*(T>)
.TP 
--timeout=\fIseconds\fR, -T \fIseconds\fR
Sets the timeout for connections to remote repositories, use 0 for no timeout (default: 20).
.TP 
--verbose[=\fIflags\fR], -d
Produce verbose output. If no \*(T<flags\*(T> are given then be verbose about everything, otherwise just be verbose about the flags which are present. Allowed flags include: \*(T<all\*(T>, \*(T<loader\*(T>.
