'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH "ceylon import-jar" 1 "9 October 2014" "" ""
.SH NAME
ceylon import-jar \- Imports a jar file into a Ceylon module repository
.SH SYNOPSIS
'nh
.fi
.ad l
\fBceylon import-jar\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[--cacherep=\fIurl\fR] [--cwd=\fIdir\fR] [--define=\fIkey>=<value\fR...] [--descriptor=\fIfile\fR] [--dry-run] [--force] [--maven-overrides=\fIurl\fR] [--no-default-repositories] [--offline] [--out=\fIurl\fR] [--pass=\fIsecret\fR] [--rep=\fIurl\fR...] [--show-classes] [--show-suggestions] [--sysrep=\fIurl\fR] [--timeout=\fIseconds\fR] [--update-descriptor] [--user=\fIname\fR] [--verbose[=\fIflags\fR]] [--] {module} {jar-file}
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
Imports the given \*(T<<jar\-file>\*(T> using the module name and version given by \*(T<<module>\*(T> into the repository named by the \*(T<\-\-out\*(T> option.
.PP
\*(T<<module>\*(T> is a module name and version separated with a slash, for example \*(T<com.example.foobar/1.2.0\*(T>.
.PP
\*(T<<jar\-file>\*(T> is the name of the Jar file to import.
.SH OPTIONS
.TP 
--cacherep=\fIurl\fR
Specifies the folder to use for caching downloaded modules. (default: \*(T<~/.ceylon/cache\*(T>)
.TP 
--cwd=\fIdir\fR
Specifies the current working directory for this tool. (default: the directory where the tool is run from)
.TP 
--define=\fIkey>=<value\fR, -D \fIkey>=<value\fR
Set a system property
.TP 
--descriptor=\fIfile\fR
Specify a module.xml or module.properties file to be used as the module descriptor
.TP 
--dry-run
Performs all the sanity checks but does not publish the JAR.
.TP 
--force
Skips sanity checks and forces publication of the JAR.
.TP 
--maven-overrides=\fIurl\fR
Specifies the xml file to use to load Maven artifact overrides.
.TP 
--no-default-repositories
Indicates that the default repositories should not be used.
.TP 
--offline, -L
Enables offline mode that will prevent connections to remote repositories.
.TP 
--out=\fIurl\fR, -o \fIurl\fR
Specifies the output module repository (which must be publishable). (default: \*(T<./modules\*(T>)
.TP 
--pass=\fIsecret\fR
Sets the password for use with an authenticated output repository(no default).
.TP 
--rep=\fIurl\fR
Specifies a module repository containing dependencies. Can be specified multiple times. (default: \*(T<modules\*(T>, \*(T<~/.ceylon/repo\*(T>, \*(T<http://modules.ceylon\-lang.org/repo/1\*(T>)
.TP 
--show-classes
Shows all external classes that are not declared as imports instead of their packages only.
.TP 
--show-suggestions
Shows suggestions for modules based on missing package names (this can take a long time).
.TP 
--sysrep=\fIurl\fR
Specifies the system repository containing essential modules. (default: \*(T<$CEYLON_HOME/repo\*(T>)
.TP 
--timeout=\fIseconds\fR, -T \fIseconds\fR
Sets the timeout for connections to remote repositories, use 0 for no timeout (default: 20).
.TP 
--update-descriptor
Whenever possible will create or adjust the descriptor file with the necessary definitions.
.TP 
--user=\fIname\fR
Sets the user name for use with an authenticated output repository(no default).
.TP 
--verbose[=\fIflags\fR], -d
Produce verbose output. If no \*(T<flags\*(T> are given then be verbose about everything, otherwise just be verbose about the flags which are present. Allowed flags include: \*(T<all\*(T>, \*(T<loader\*(T>.
.SH REPOSITORIES
Repositories like those specified with the \*(T<\-\-rep\*(T> or \*(T<\-\-out\*(T> options can be file paths, HTTP urls to remote servers or can be names of repositories when prepended with a \*(T<+\*(T> symbol. These names refer to repositories defined in the configuration file or can be any of the following predefined names \*(T<+SYSTEM\*(T>, \*(T<+CACHE\*(T>, \*(T<+LOCAL\*(T>, \*(T<+USER\*(T> or \*(T<+REMOTE\*(T>. For more information see http://ceylon-lang.org/documentation/1.0/reference/tool/config
